version: '3.9'

services:
  app:
    restart: unless-stopped
    build: .
    networks:
      app_net:
        ipv4_address: ${APP_ADDR}
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}

    volumes:
      - ./app:/code/app:rw
      - ./migrations:/code/migrations:rw
    command: uvicorn app.main:app --reload --workers ${APP_WORKER_COUNT} --host 0.0.0.0 --port ${APP_PORT}

  postgres:
    restart: unless-stopped
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      app_net:
        ipv4_address: ${POSTGRES_ADDR}

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./frontend:/www/data/static
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    environment:
      NGINX_PORT: ${NGINX_PORT}
      APP_ADDR: ${APP_ADDR}
      APP_PORT: ${APP_PORT}
    networks:
      app_net:
        ipv4_address: ${NGINX_ADDR}
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"


networks:
  app_net:
    ipam:
      config:
        - subnet: 172.12.0.0/24
