"""add is_complete filed to todo

Revision ID: f16555afad43
Revises: b1a20969838c
Create Date: 2022-03-25 19:39:27.841220

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f16555afad43"
down_revision = "b1a20969838c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todo", sa.Column("is_complete", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todo", "is_complete")
    # ### end Alembic commands ###
